<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Intern Inquiries - SDCA OJT Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
    <style>:root { --sdca-red: #800000; } body { min-height: 100vh; margin: 0; background: #f4f6f9; color: #25292d; } .app-container { display: flex; min-height: 100vh; } .sidebar { width: 240px; height: 100vh; position: fixed; inset: 0 auto 0 0; z-index: 1030; background: #fff; box-shadow: 4px 0 15px rgba(0,0,0,.1); overflow-y: auto; } .sidebar-logo { max-height: 52px; width: auto; } .sidebar-menu { list-style: none; padding: 0; margin: 12px 0 0; } .sidebar-menu a { color: #495057; padding: 12px 20px; display: flex; align-items: center; gap: 12px; text-decoration: none; font-size: .92rem; font-weight: 500; border-left: 4px solid transparent; } .sidebar-menu a:hover, .sidebar-menu li.active a { background: #fff5f5; color: var(--sdca-red); border-left-color: var(--sdca-red); font-weight: 700; } .main-content { flex: 1; min-width: 0; margin-left: 240px; } .top-navbar { height: 48px; background: var(--sdca-red); position: fixed; top: 0; left: 240px; width: calc(100% - 240px); z-index: 1020; } .page-wrap { max-width: 1120px; padding-top: 76px; padding-bottom: 28px; } .inquiry-card { border-left: 4px solid var(--sdca-red); } .reply-preview { background: #edf7f1; border-left: 3px solid #198754; } @media (max-width: 768px) { .sidebar { width: 76px; } .sidebar-menu span { display: none; } .sidebar-menu a { justify-content: center; padding: 15px 8px; } .main-content { margin-left: 76px; } .top-navbar { left: 76px; width: calc(100% - 76px); } .top-navbar .navbar-brand span { display: none; } }</style>
</head>
<body>
<div class="app-container">
    <aside class="sidebar"><div class="p-3 text-center border-bottom"><a href="<?= base_url('admin'); ?>"><img src="<?= base_url('assets/images/sdcalogo.png'); ?>" alt="SDCA Logo" class="sidebar-logo img-fluid"></a><hr class="my-2"><small class="text-muted fw-semibold"><i class="bi bi-shield-lock me-1"></i>ADMIN PORTAL</small></div><ul class="sidebar-menu"><li><a href="<?= base_url('admin'); ?>"><i class="fas fa-home"></i><span>Dashboard</span></a></li><li><a href="<?= base_url('admin'); ?>#intern-management"><i class="fas fa-users"></i><span>Intern Management</span></a></li><li><a href="<?= base_url('admin'); ?>#ojt-management"><i class="fas fa-user-clock"></i><span>OJT Management</span></a></li><li><a href="<?= base_url('admin'); ?>#dtr-records"><i class="fas fa-calendar-alt"></i><span>DTR and Time Records</span></a></li><li><a href="<?= base_url('admin'); ?>#analytics"><i class="fas fa-chart-line"></i><span>Analytics and Reports</span></a></li><li><a href="<?= base_url('admin/announcements'); ?>"><i class="bi bi-megaphone"></i><span>Announcements</span></a></li><li class="active"><a href="<?= base_url('admin/inquiries'); ?>"><i class="bi bi-question-circle"></i><span>Inquiries &amp; Concerns</span></a></li><li><a href="<?= base_url('admin'); ?>#admin-tools"><i class="fas fa-cogs"></i><span>Administrative Tools</span></a></li></ul></aside>
    <div class="main-content">
        <nav class="top-navbar navbar navbar-dark p-0 shadow-sm"><div class="container-fluid px-4 h-100 d-flex align-items-center justify-content-between"><a class="navbar-brand fw-bold d-flex align-items-center h-100 m-0" href="<?= base_url('admin'); ?>"><i class="bi bi-clock-history me-2"></i><span>OJT Hours Tracker</span></a><div class="dropdown"><button class="btn text-white dropdown-toggle" type="button" data-bs-toggle="dropdown"><i class="bi bi-person-circle me-1"></i>Administrator</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="<?= base_url('admin'); ?>">Admin Dashboard</a></li><li><a class="dropdown-item text-danger" href="<?= base_url('auth/logout'); ?>">Logout</a></li></ul></div></div></nav>
<main class="container page-wrap">
    <div class="mb-4"><h2 class="fw-bold mb-1">Intern Inquiries</h2><p class="text-muted mb-0">Review concerns submitted through the intern support portal.</p></div>
    <?php if ($this->session->flashdata('success')): ?><div class="alert alert-success alert-dismissible fade show"><?= html_escape($this->session->flashdata('success')); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
    <?php if ($this->session->flashdata('error')): ?><div class="alert alert-danger alert-dismissible fade show"><?= html_escape($this->session->flashdata('error')); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
    <?php if (!empty($inquiries)): foreach ($inquiries as $inquiry): ?><article class="card inquiry-card shadow-sm mb-3"><div class="card-body"><div class="d-flex justify-content-between align-items-start gap-3"><div><h5 class="mb-1"><?= html_escape(trim($inquiry['first_name'] . ' ' . $inquiry['last_name'])); ?></h5><small class="text-muted d-block mb-2"><?= html_escape($inquiry['email']); ?> | <?= date('M d, Y g:i A', strtotime($inquiry['created_at'])); ?></small><span class="badge bg-secondary mb-2"><?= html_escape($inquiry['category']); ?></span><p class="mb-0"><?= nl2br(html_escape($inquiry['message'])); ?></p></div><span class="badge <?= $inquiry['status'] === 'Answered' ? 'bg-success' : ($inquiry['status'] === 'Closed' ? 'bg-secondary' : 'bg-warning text-dark'); ?>"><?= html_escape($inquiry['status']); ?></span></div><?php if (!empty($inquiry['admin_reply'])): ?><div class="reply-preview p-3 mt-3"><strong class="d-block mb-1">Current Reply</strong><?= nl2br(html_escape($inquiry['admin_reply'])); ?></div><?php endif; ?><form action="<?= base_url('admin/reply_to_inquiry/' . (int)$inquiry['id']); ?>" method="post" class="mt-3"><label class="form-label fw-semibold" for="reply<?= (int)$inquiry['id']; ?>">Reply to This Inquiry</label><textarea class="form-control" id="reply<?= (int)$inquiry['id']; ?>" name="admin_reply" rows="3" required><?= html_escape($inquiry['admin_reply']); ?></textarea><button type="submit" class="btn btn-danger btn-sm mt-2"><i class="bi bi-reply-fill me-1"></i>Send Reply</button></form></div></article><?php endforeach; else: ?><div class="card shadow-sm border-0"><div class="card-body text-center py-5 text-muted"><i class="bi bi-inbox display-5 d-block mb-3"></i>No intern inquiries yet.</div></div><?php endif; ?>
</main>
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
