<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DTR Report - SDCA OJT Tracker</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; border-bottom: 3px solid #a12124; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { color: #a12124; margin: 0; }
        .header p { margin: 5px 0; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #a12124; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        .badge { padding: 3px 8px; border-radius: 3px; font-size: 11px; }
        .badge-success { background-color: #28a745; color: white; }
        .badge-warning { background-color: #ffc107; color: black; }
        .badge-secondary { background-color: #6c757d; color: white; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ST. DOMINIC COLLEGE OF ASIA</h1>
        <p>OJT Hours Tracker - DTR Audit Report</p>
        <p><strong>Report Period:</strong> <?= date('F d, Y', strtotime($start_date)); ?> to <?= date('F d, Y', strtotime($end_date)); ?></p>
        <p><strong>Generated:</strong> <?= $generated_at; ?></p>
    </div>

    <h3>Intern Summary (<?= ucfirst($report_type); ?>)</h3>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Intern Name</th>
                <th>Email</th>
                <th>School/Department</th>
                <?php if ($include_hours): ?>
                <th>Total Hours</th>
                <?php endif; ?>
                <?php if ($include_status): ?>
                <th>Status</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($interns)): $counter = 1; foreach ($interns as $intern): ?>
            <tr>
                <td><?= $counter++; ?></td>
                <td><strong><?= html_escape(trim($intern['first_name'] . ' ' . $intern['last_name'])); ?></strong></td>
                <td><?= html_escape($intern['email']); ?></td>
                <td><?= html_escape($intern['school'] ?? 'N/A'); ?></td>
                <?php if ($include_hours): ?>
                <td><?= number_format((float)$intern['total_hours'], 2); ?> hrs</td>
                <?php endif; ?>
                <?php if ($include_status): ?>
                <td>
                    <?php
                    $status = $intern['account_status'];
                    $badge_class = 'badge-secondary';
                    if ($status === 'approved' || $status === 'active') $badge_class = 'badge-success';
                    elseif ($status === 'pending') $badge_class = 'badge-warning';
                    ?>
                    <span class="badge <?= $badge_class; ?>"><?= ucfirst($status); ?></span>
                </td>
                <?php endif; ?>
            </tr>
            <?php endforeach; else: ?>
            <tr>
                <td colspan="<?= 4 + ($include_hours ? 1 : 0) + ($include_status ? 1 : 0); ?>" class="text-center">
                    No records found for the selected period.
                </td>
            </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official document generated by the SDCA OJT Hours Tracker System.</p>
        <p>For questions or concerns, contact the administrator.</p>
    </div>

    <script>
        window.onload = function() {
            window.print();
        };
    </script>
</body>
</html>